name: Update Status Badges

on:
  push:
    branches: [main]
  schedule:
    # Update badges daily
    - cron: '0 0 * * *'

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage
        run: npm run test:coverage
        env:
          CI: true

      - name: Update README badges
        run: |
          # Get current test status
          TEST_STATUS=$(echo ${{ job.status }} | tr '[:upper:]' '[:lower:]')
          
          # Get coverage percentage
          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          
          # Generate badge colors
          if (( $(echo "$COVERAGE >= 90" | bc -l) )); then
            COVERAGE_COLOR="brightgreen"
          elif (( $(echo "$COVERAGE >= 80" | bc -l) )); then
            COVERAGE_COLOR="yellow"
          else
            COVERAGE_COLOR="red"
          fi
          
          # Update README.md with current badges
          sed -i "s|coverage-[0-9]*%-.*|coverage-${COVERAGE}%-${COVERAGE_COLOR}|g" README.md
          
          echo "Updated badges: Tests: $TEST_STATUS, Coverage: $COVERAGE%"

      - name: Generate test report badge
        uses: jaywcjlove/generated-badges@main
        with:
          label: Tests
          status: ${{ job.status }}
          color: ${{ job.status == 'success' && 'brightgreen' || 'red' }}
          output: badges/tests.svg

      - name: Generate coverage badge
        uses: jaywcjlove/generated-badges@main
        with:
          label: Coverage
          status: $(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')%
          color: brightgreen
          output: badges/coverage.svg

      - name: Commit badge updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add badges/ README.md
          git diff --staged --quiet || git commit -m "Update status badges [skip ci]"
          git push